services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - /var/www/node_modules
        networks:
            - erp-network
        depends_on:
            - db
            - redis

    nginx:
        image: nginx:alpine
        container_name: erp-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - erp-network
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: erp-mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - erp-network

    redis:
        image: redis:alpine
        container_name: erp-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - erp-network

networks:
    erp-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
